version: 1.0
provider:
  name: openfaas
  gateway: http://aeaf98ecd4b5b4f818de564cba531498-1255126595.eu-central-1.elb.amazonaws.com:8080

functions:
  vlp-vehicle-service:
    image: ghcr.io/nazzzus/vlp-vehicle-service:openfaas
    skip_build: true
    skip_push: true
    secrets:
      - mongodb-uri
    environment:
      fprocess: "/usr/bin/entrypoint.sh"
      PORT: "8082"
      MONGO_URI: "mongodb+srv://nazir_db_user:Nasu2026@cluster0.cdvnklb.mongodb.net/vlp?retryWrites=true&w=majority&appName=Cluster0"
      MONGO_DB: "vlp"
      MONGO_COLLECTION: "vehicles"