version: 1.0
provider:
  name: openfaas
  gateway: http://aeaf98ecd4b5b4f818de564cba531498-1255126595.eu-central-1.elb.amazonaws.com:8080

functions:
  vlp-vehicle-service:
    image: ghcr.io/nazzzus/vlp-vehicle-service:openfaas
    skip_build: true
    skip_push: true
    environment:
      fprocess: "/usr/bin/entrypoint.sh"
      PORT: "8082"
      MONGO_URI: "mongodb+srv://nazirm10:nazirm10@vlp-benchmark-m10.bvhn2g.mongodb.net/vlp"
      MONGO_DB: "vlp"
      MONGO_COLLECTION: "vehicles"