version = 0.1

[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MongoUri=\"${MONGO_URI}\" MongoDatabase=\"vlp\" MongoCollection=\"vehicles\""
image_repositories = []

[default.global.parameters]
region = "eu-central-1"
