name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  go-ci:
    name: Go (workspace) - test & build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.5"
          cache: true

      - name: Go env
        run: |
          go version
          go env

      - name: Download deps
        run: |
          go work sync
          go mod download

      - name: Vet (vehicle-service)
        run: |
          cd services/vehicle-service
          go vet ./...

      - name: Test (vehicle-service)
        run: |
          cd services/vehicle-service
          go test ./... -count=1


      - name: Build (vehicle-service http)
        run: |
          cd services/vehicle-service
          go build ./cmd/http

      - name: Build (vehicle-service lambda)
        run: |
          cd services/vehicle-service
          go build ./cmd/lambda